spring:
  datasource:
    url: jdbc:mysql:aws://db-adv.cluster-ckxwbh1j1zs1.ap-southeast-1.rds.amazonaws.com/adv_test?serverTimezone=Asia/Jakarta&useSSL=false
    username: root
    password: Password123$
    hikari:
      connection-test-query: SELECT 1;
      connection-timeout: 30000
      driver-class-name: software.aws.rds.jdbc.mysql.Driver
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
      validation-timeout: 28000
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: false
