spring:
  datasource:
    url: jdbc:h2:file:/Users/feliz/Documents/SDEBackend/mysql-employee-shceme/Mysql-Employee-Scheme/data/memory
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher